PLAT-505 Trial site install in build hook

diff --git a/.platform.app.yaml b/.platform.app.yaml
--- a/.platform.app.yaml
+++ b/.platform.app.yaml
@@ -74,10 +74,6 @@ hooks:
         cp /app/ci/platform/settings.php /app/web/sites/default/settings.php
         cp /app/ci/platform/settings.platformsh.php /app/web/sites/default/settings.platformsh.php
 
-    # We run deploy hooks after your application has been deployed and started.
-    deploy: |
-        set -e
-
         # Re-install the site if this hasn't been installed yet for this branch, or we are on develop
         if [ $PLATFORM_ENVIRONMENT = "develop" ] || [ ! -f tmp/$PLATFORM_ENVIRONMENT.installed ]; then
           echo ">>> Re-installing CR profile"
@@ -88,12 +84,16 @@ hooks:
           drush en cr_default_content -y
           touch "tmp/${PLATFORM_ENVIRONMENT}.installed"
           echo ">>> End re-installing CR profile"
-        else
-          echo ">>> No re-installation of the profile required, just a simple update!"
-          phing config:import
-          cd web/
-          drush cr
         fi
+
+    # We run deploy hooks after your application has been deployed and started.
+    deploy: |
+        set -e
+
+        echo ">>> No re-installation of the profile required, just a simple update!"
+        phing config:import
+        cd web/
+        drush cr
 
 # The configuration of scheduled execution.
 crons:
